services:
  mongodb:
    image: mongo:8.0
    volumes:
      - backend${BE_VERSION:-v4}_mongodb_data:/data/db
      # Init and seed files are loading the example dataset into the database, which are
      # then available in the frontend.
      # - ./config/init.sh:/docker-entrypoint-initdb.d/init.sh
      # - ./config/seed:/seed
    labels:
      # Adding a label to keep this service out of traefik
      - traefik.enable=false
    environment:
      BE_VERSION: ${BE_VERSION:-v4}
      DEV: ${DEV:+dev-}
    restart: on-failure

volumes:
  backendv3_mongodb_data:
    driver: local
  backendv4_mongodb_data:
    driver: local
